# Site settings
title: veevo
email: contact@veevo.org
description: > # this means to ignore newlines until "baseurl:"
  veevo.org | Know thyself
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: veevo
github_username:  veevo

# Build settings
markdown: kramdown
